[project]
name = "fake-gen"
version = "0.1.0"
description = "Generates fake data for testing purposes."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "faker>=37.5.3",
]

[dependency-groups]
dev = [
    "ruff>=0.12.9",
]
